name: main

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: acessKey
        run: echo "The secret is ${{ secrets.acessKey }}"
